CREATE TABLE "public"."ProxtConfigs"("Id" uuid NOT NULL,"MichCredentialID" text,"MichCredentialPwd" text,"MichCustomerId" text,"MichMeDomain" text,"MichInnerDomain" text,"MichAD" text,"MichADAccount" text,"MichADAccount2" text,"MichADAccount3" text,"MichLoginHttps" text,"MichAppLable" text,"MichAesKey" text,"MichMaxWaitAskSec" text,"MichTaskTitle" text,"MichTaskMessage" text,"MichReviewerTaskMessage" text,"AuthSource" text,"AuthType" text,"ClientApi" text,"MichLoginUseTailName" text,"MichPki" text,"MichLanguageLable" text,"EmailServerAddr" text,"EmailServerPort" text,"EmailAccount" text,"EmailPass" text,"EmailSmtpSSL" text,CONSTRAINT "PK_public.ProxtConfigs" PRIMARY KEY ("Id"));
CREATE TABLE "public"."UserAccounts"("Id" uuid NOT NULL,"MfaProxyAccount" text,"MfaProxyMail" text,"MfaProxyAccPwd" text,CONSTRAINT "PK_public.UserAccounts" PRIMARY KEY ("Id"));
CREATE TABLE "public"."__MigrationHistory"("MigrationId" varchar(150) NOT NULL,"ContextKey" varchar(300) NOT NULL,"Model" bytea NOT NULL,"ProductVersion" varchar(32) NOT NULL,CONSTRAINT "PK_public.__MigrationHistory" PRIMARY KEY ("MigrationId","ContextKey"));
CREATE TABLE "public"."AuthSettings"("Id" uuid NOT NULL,"Owner" text,"Application" text,"Type" text,"Reviewer" text,"RuleAnd" text,"Question" text,"Answer" text,CONSTRAINT "PK_public.AuthSettings" PRIMARY KEY ("Id"));
CREATE TABLE "public"."MultiVerifys"("Id" uuid NOT NULL,"MfaAccount" text,"MfaAccPwd" text,"PremissionsUser" text,"MultiFlag" text,"MultiWin" text,"MultiVPN" text,CONSTRAINT "PK_public.MultiVerifys" PRIMARY KEY ("Id"));
CREATE TABLE "public"."EmailVerifications"("Id" uuid NOT NULL,"UserAccount" text,"Email" text,"Created" int8 NOT NULL,"Signature" text,"Result" text,CONSTRAINT "PK_public.EmailVerifications" PRIMARY KEY ("Id"));
ALTER TABLE "public"."UserAccounts" ADD "MfaEnableAlternative" text DEFAULT 'false';
ALTER TABLE "public"."UserAccounts" ADD "MfaAlternativeExpires" int8 NOT NULL DEFAULT 0;
ALTER TABLE "public"."ProxtConfigs" ADD "EmailSenderName" text;
ALTER TABLE "public"."ProxtConfigs" ADD "EmailSenderAddress" text;
ALTER TABLE "public"."UserAccounts" ADD "MfaErrorCount" int4 NOT NULL DEFAULT 0;
ALTER TABLE "public"."ProxtConfigs" ADD "MichLDAP" text;
ALTER TABLE "public"."ProxtConfigs" ADD "BindDN" text;
ALTER TABLE "public"."ProxtConfigs" ADD "BindPassword" text;
ALTER TABLE "public"."ProxtConfigs" ADD "BaseDC" text;
ALTER TABLE "public"."ProxtConfigs" ADD "SearchFilter" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LoginTaskMessage" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LoginVerification" text;
ALTER TABLE "public"."ProxtConfigs" ADD "MichRadius" text;
ALTER TABLE "public"."ProxtConfigs" ADD "RadiusServer" text;
ALTER TABLE "public"."ProxtConfigs" ADD "RadiusSecret" text;
ALTER TABLE "public"."ProxtConfigs" ADD "RadiusPort" text;
ALTER TABLE "public"."ProxtConfigs" ADD "RadiusTimeout" text;
ALTER TABLE "public"."ProxtConfigs" ADD "RiskDetection" text;
ALTER TABLE "public"."EmailVerifications" ADD "Application" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LogoUrl" text;
CREATE TABLE "public"."MobilePushes"("Id" uuid NOT NULL,"UserAccount" text,"Email" text,"Application" text,"Created" int8 NOT NULL,"Signature" text,"Result" text,CONSTRAINT "PK_public.MobilePushes" PRIMARY KEY ("Id"));
CREATE TABLE "public"."UserAccountV2"("Id" uuid NOT NULL,"uid" text,"source" text,"pass" text,"enable" text,CONSTRAINT "PK_public.UserAccountV2" PRIMARY KEY ("Id"));
CREATE INDEX "UserAccountV2_IX_uid" ON "public"."UserAccountV2" ("uid");
ALTER TABLE "public"."ProxtConfigs" ADD "Manage_search" text;
ALTER TABLE "public"."ProxtConfigs" ADD "AD_Account" text;
ALTER TABLE "public"."ProxtConfigs" ADD "AD_Password" text;
ALTER TABLE "public"."ProxtConfigs" ADD "User_role" text;
ALTER TABLE "public"."UserAccountV2" ADD "role" text;
ALTER TABLE "public"."ProxtConfigs" ADD "Passwordless" text;
CREATE TABLE "public"."SamlIdpAttributes"("Id" uuid NOT NULL,"SPId" uuid NOT NULL,"AttrKey" text,"KeypasscoAuthValue" text,CONSTRAINT "PK_public.SamlIdpAttributes" PRIMARY KEY ("Id"));
CREATE TABLE "public"."SamlIdpConfigs"("Id" uuid NOT NULL,"Enable" int4 NOT NULL,"Issuer" text,"SignatureAlgorithm" text,"OrganizationName" text,"OrganizationNameDisplayName" text,"OrganizationNameURL" text,"SubjectConfirmationLifetime" int4 NOT NULL,"IssuedTokenLifetime" int4 NOT NULL,"IdpCertificate" text,"IdpCertificatePassword" text,"EnablePush" text,CONSTRAINT "PK_public.SamlIdpConfigs" PRIMARY KEY ("Id"));
CREATE TABLE "public"."SamlIdpContacts"("Id" uuid NOT NULL,"Type" text,"Company" text,"GivenName" text,"SurName" text,"EmailAddress" text,"TelephoneNumber" text,CONSTRAINT "PK_public.SamlIdpContacts" PRIMARY KEY ("Id"));
CREATE TABLE "public"."SamlIdpTrustSPs"("SPId" uuid NOT NULL,"Issuer" text,"Metadata" text,"AcsURL" text,"SloURL" text,"HasAcsURLHeader" int4 NOT NULL,"SignAuthnRequest" int4 NOT NULL,"SPCertificate" text,"SPCertificatePassword" text,"EncryptedResponse" int4 NOT NULL,"Created" int8 NOT NULL,CONSTRAINT "PK_public.SamlIdpTrustSPs" PRIMARY KEY ("SPId"));
ALTER TABLE "public"."ProxtConfigs" ADD "LdapsCert" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LdapsCertUser" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LdapsCertPwd" text;
ALTER TABLE "public"."ProxtConfigs" ADD "LdapsDomain" text;
ALTER TABLE "public"."UserAccountV2" ADD "password" text;
CREATE TABLE "public"."UserUuidMappings"("Id" uuid NOT NULL,"uid" text,"UserId" text,"UuId" text,"Uid" text,CONSTRAINT "PK_public.UserUuidMappings" PRIMARY KEY ("Id"));
ALTER TABLE "public"."SamlIdpConfigs" ADD "EnableNetSuite" int4;
ALTER TABLE "public"."SamlIdpConfigs" ADD "NetSuiteAccountID" text;
CREATE TABLE "public"."CounterReportConfigs" ("Id" uuid NOT NULL, "EmailList" text NULL, "EnableScheduleWeek" int4 DEFAULT 0 NOT NULL, "EnableScheduleMonth" int4 DEFAULT 0 NOT NULL, "ScheduleWeekDay" int4 NULL, "ScheduleMonthDay" int4 NULL, CONSTRAINT pk_counterreportconfigs PRIMARY KEY ("Id"));
ALTER TABLE "public"."CounterReportConfigs" ADD "MasterIP" text;
ALTER TABLE "public"."CounterReportConfigs" ADD "ScheduleWeekTime" text;
ALTER TABLE "public"."CounterReportConfigs" ADD "ScheduleMonthTime" text;
CREATE TABLE "public"."GinaLoginRecords" ("Id" uuid NOT NULL, "ComputerName" text NOT NULL, "LoginTime" int8 NOT NULL, "LoginUser" text NOT NULL, "AgentUser" text NOT NULL, "KeypascoAccount" text NOT NULL, "Result" int4 NOT NULL, "CreatedTime" int8 NOT NULL, CONSTRAINT "PK_GinaLoginRecords" PRIMARY KEY ("Id"));
CREATE TABLE "public"."TotpUserMappings" ("Id" uuid NOT NULL, "Uid" text NOT NULL, "Domain" text NOT NULL, "Secret" text NOT NULL, "Created" int8 NOT NULL, CONSTRAINT "PK_TotpUserMappings" PRIMARY KEY ("Id"));
CREATE TABLE "public"."TotpAuthedHistories" ("Id" uuid NOT NULL, "Uid" text NOT NULL, "Domain" text NOT NULL, "TotpCode" text NOT NULL, "Created" int8 NOT NULL, CONSTRAINT "PK_TotpAuthedHistories" PRIMARY KEY ("Id"));
ALTER TABLE "public"."UserAccountV2" ADD "upn" text;
CREATE TABLE "public"."AdSetting" ("Id" uuid NOT NULL, "domain" text, "nickname" text, "isSearch" BOOLEAN, "BaseDN" text, "searchScope" text, "updateTime" int2,"updateProxy" text,"Ldapsport" text,"LdapsCredentialsLocation" text,"LdapsCredentialAccount" text ,"LdapsCredentialsPassword" text,"AdPort" text,"AdAccount" text,"AdPassword" text,"SSL" BOOLEAN,"activation" text,CONSTRAINT "PK_public.ADSetting" PRIMARY KEY ("Id"));
ALTER TABLE "public"."SamlIdpConfigs" ADD "NoCaptcha" int4 DEFAULT 1;
ALTER TABLE "public"."SamlIdpConfigs" ADD "ForceDomain" text;
ALTER TABLE "public"."SamlIdpConfigs" ADD "Fido2BorgenUrl" text;
ALTER TABLE "public"."SamlIdpConfigs" ADD "Fido2Upn" text;
ALTER TABLE "public"."UserAccountV2" ADD "activate" text;
ALTER TABLE "public"."UserAccountV2" ADD "login_allow" text;
ALTER TABLE "public"."ProxtConfigs" ADD "CustomerApiSSLIgnore" text;
ALTER TABLE "public"."ProxtConfigs" ADD "CustomerApiAuthType" text;
ALTER TABLE "public"."ProxtConfigs" ADD "CustomerApiUsername" text;
ALTER TABLE "public"."ProxtConfigs" ADD "CustomerApiPassword" text;
ALTER TABLE "public"."ProxtConfigs" ADD "ClientApiSSLIgnore" text;
ALTER TABLE "public"."ProxtConfigs" ADD "ClientApiUsername" text;
ALTER TABLE "public"."ProxtConfigs" ADD "ClientApiPassword" text;